- name: Install php 7.4
  ansible.builtin.dnf:
    name: '@php:remi-7.4'
    state: present

- name: Install rpm packages for Open Xdmod
  ansible.builtin.package:
    name:
      - mariadb-server
      - mariadb-devel
      - httpd
      - mod_ssl
      - php-devel
      - php-pear
      - tmux
      - vim
      - nano
      - rsync
      - wget 
      - php-zip
      - php-posix
      - php-json
      - curl
      - libreoffice
      - php
      - php-mysqlnd
      - php-cli
      - php-gd
      - php-pdo
      - php-xml
      - cronie
      - logrotate
      - jq
      - chromium-headless
      - librsvg2-tools
      - perl-Image-ExifTool
      - slurm
      - munge
      - htop
      - php-mbstring
      - php-pecl-apcu
      - ca-certificates
      - munge
      - gnupg
      - sudo
      - libgcrypt-devel
      - man2html
      - man2html-core
      - lua-devel
      - http-parser-devel
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install NodeJS 16 via dnf modules
  ansible.builtin.dnf:
    name: '@nodejs:16'
    state: present

- name: Install mongodb pecl package
  community.general.pear:
    name: pecl/mongodb
    state: present
